### ISSUE TITLE
ETAG problem

### ISSUE THREAD

**Issue by gzl10g** [chiptime/odata-batch#1]
I was testing your package, and when I try PUT method, I got an etag error.
'El valor ETag '' solicitado no coincide con el valor ETag '"1d019d1c-e4ff-4380-9287-0ce6a2424c66,1"

Is it posible to include the header "IF-Match: *" on the changetset when is a PUT method.

Or is there another way to do that. 

Thank you and congratulations for your job.

**Comment by chiptime** [comment]
Hi @gzl10g,
thanks for the warning.
It seems to me that the most interesting thing could be to add support for headers by request, since they could give problems due to decimals or encoding, for example.
I hope to be able to support these days.

All the best!

**Comment by chiptime** [comment]
@gzl10g added support for custom headers for each request.
Please let me know if you can verify that it allows you to make the PUT request.

Thank you for taking your time to report this case!
